// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCDWkY_exGvWf6xA7uDU8uxcYFj46l-Bk',
    appId: '1:10335984344:web:8845c5a85c0371ab3c95ad',
    messagingSenderId: '10335984344',
    projectId: 'flutter-d2785',
    authDomain: 'flutter-d2785.firebaseapp.com',
    storageBucket: 'flutter-d2785.appspot.com',
    measurementId: 'G-2ZLE9RHRDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLnRspuPhTsB9iO4DPq5AYsascd21pwcw',
    appId: '1:10335984344:android:f72340d8f1b953b73c95ad',
    messagingSenderId: '10335984344',
    projectId: 'flutter-d2785',
    storageBucket: 'flutter-d2785.appspot.com',
  );
}
